Add initial files with example design
chingu-voyages/v46-tier2-team-16 pull request #20
Opened 2023-10-16 13:50 UTC by NishaVijai

2023-10-16 14:18 UTC, Alexandra2888 requested changes

2023-10-16 14:18 UTC, Alexandra2888 commented on src/components/Footer/Footer.jsx
year must be changed :)

2023-10-16 15:06 UTC, NishaVijai commented on src/components/Footer/Footer.jsx
I have updated the year :-) thank you.

2023-10-16 18:31 UTC, ocsiddisco approved these changes

2023-10-17 08:51 UTC, Alexandra2888 approved these changes

2023-10-17 10:01 UTC, merged